name: Docker build and run

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker image
        run: docker build -t kohlantabottest:latest .

      - name: Run Docker container
        run: docker run -d --name kohlantabot kohlantabottest:latest

      - name: Verify the container is running
        run: docker ps | grep kohlantabot

      - name: Stop and remove container
        run: |
          docker stop kohlantabot
          docker rm kohlantabot